name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11' ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: ./gradlew test
